[tool.poetry]
name = "src"
version = "0.1.0"
description = ""
authors = ["itallominatti <itallominatti@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11.9"
pylint = "^3.3.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
